### ISSUE TITLE
Более короткая запись

### ISSUE THREAD

**Issue by pecourses** [schaslivchik/functionsHomework#1]
https://github.com/schaslivchik/functionsHomework/blob/cb0b76ed22a1915de7b2b4fe5514a4fe09d03471/index.js#L6
- можно записать лаконичнее

**Comment by schaslivchik** [comment]
function isWorkingAgePerson(age) {
  return agePerson = (age >= 16 && age <= 65) ? true : false;
}
console.log(isWorkingAgePerson(18));

**Comment by pecourses** [comment]
```
function isWorkingAgePerson(age) {
  return age >= 16 && age <= 65;
}
```
age >= 16 && age <= 65 как результат и дает то булевское значение, которое нам нужно вернуть
