### ISSUE TITLE
лишняя ветка

### ISSUE THREAD

**Issue by pecourses** [schaslivchik/functionsHomework#3]
https://github.com/schaslivchik/functionsHomework/blob/cb0b76ed22a1915de7b2b4fe5514a4fe09d03471/index.js#L35
- если эта ветка лишняя, то можно сократить запись функции

**Comment by schaslivchik** [comment]
function checkMultiplicity(a, b) {
  return (a % b === 0) ? true : false;
}
console.log(checkMultiplicity(15, 5));

**Comment by pecourses** [comment]
Да, плюс еще можно записать короче, как с определением работоспособного возраста.
