### ISSUE TITLE
лаконичная запись

### ISSUE THREAD

**Issue by pecourses** [schaslivchik/functionsHomework#4]
https://github.com/schaslivchik/functionsHomework/blob/cb0b76ed22a1915de7b2b4fe5514a4fe09d03471/index.js#L47
- можно записать в виде

 `return a <= b + c && b <= c + a && c <= b + a;`

**Comment by schaslivchik** [comment]
function isCorectTriangle(a, b, c) {
  return corectTriangle = (a <= b + c && b <= c + a && c <= b + a) ? true : false; 
}
console.log(isCorectTriangle(5, 6, 8));

**Comment by pecourses** [comment]
Пример в задании по определению работоспособного возраста
